# Generated by Django 4.2.2 on 2023-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ID', models.CharField(max_length=10)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Date_of_Birth', models.DateField()),
                ('Mobile_No', models.IntegerField()),
                ('Organization', models.CharField(max_length=20)),
                ('Date_of_join', models.DateField()),
                ('Salary', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('Vaccine_status', models.BooleanField()),
                ('Display_picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
    ]
