# Generated by Django 4.2.2 on 2023-06-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_alter_employee_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Mobile_No',
            field=models.CharField(max_length=10),
        ),
    ]
